version: 0.2

phases:
  install:
    commands:
      - echo Instalando Node
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Instalando dependencias
      - npm install
  build:
    commands:
      - echo Corriendo tests
      - npm run test
      - echo Creando build
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
